language: node_js
node_js:
- 12
services:
- docker
env:
- NODE_ENV=production
install:
- npm install
- npm install -g typescript
script:
- npm test
after_success:
  - npm run build
# - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
# - docker build -t kemarskiy/color-pick:1.0 .
# - docker push kemarskiy/color-pick
# before_install:
# - openssl aes-256-cbc -K $encrypted_8a8f606118a6_key -iv $encrypted_8a8f606118a6_iv
#   -in deploy_rsa.enc -out deploy_rsa -d
# - eval "$(ssh-agent -s)"
# - cp deploy_rsa ~/.ssh/deploy_rsa
# - chmod 600 ~/.ssh/deploy_rsa
# - ssh-add ~/.ssh/deploy_rsa
# deploy:
# - provider: script
#   skip_cleanup: true
#   script: "scripts/deploy.sh"
#   on:
#     branch: master